### ISSUE TITLE
Command Line arguments issue

### ISSUE THREAD

**Issue by Asad-Shoaib** [delicb/oso-go-tutorial#1]
HI, 

I was trying to run the project by using go run main.go but i'm getting the following errors and unable to resolved them so far.

macbook@Macbooks-MBP oso-go-tutorial-main % go run main.go                     
# command-line-arguments
./main.go:25:22: undefined: NewAuthorizer
./main.go:38:13: undefined: NewDBManager
./main.go:47:12: undefined: NewHTTPHandler
macbook@Macbooks-MBP oso-go-tutorial-main % g

Also, is there any resource for building a simple login/register functionality with oso in Golang, looking forward to your kind response, thanks.

**Comment by delicb** [comment]
Hi @Asad-Shoaib,

Just running `go run main.go` will not be enough, since `main.go` does not contain the whole program. Some parts of it, like authorization engine, HTTP server, and database manager are defined in `authorization.go`, `db.go` and `server.go`. 

You should build the project first and run the executable you get:
```
$ go build
$ ./oso-go-tutorial
2021/04/12 11:05:31 Starting HTTP server on 127.0.0.1:8000
```
This should give you a running server at port 8000. In order to test it, you can try it out in a second terminal:
```
$ curl http://localhost:8000/
hello guest user
```

Regarding building authentication (login/register) - that is not really what OSO does. Once you already have that, OSO can tell you if a user is authorized (has permission) to perform an action on the object. In this tutorial, I assume that the user is authenticated if there is an HTTP header `User` with an email that matches one in the database. If you need a simple example, you might want to try to add to this tutorial ability for a client to send both username and password (e.g. base64 encode them) and verify if they match what you expect in the database, as opposed to just checking if email exists, but that hardly has anything to do with OSO.

I hope this answer helps, please let me know if you run into any problems.

**Comment by delicb** [comment]
@Asad-Shoaib Did this solve your problem?

**Comment by Asad-Shoaib** [comment]
Hi Bojan,

Yes it solved my problem, thank you so much for your help.

Kind regards,
Asad.
